from . import admin
from . import kurs_qushish
from . import kurs_uchirish
from . import kurs_tahrirlash
from . import other
from . import remove_admins
from . import statistika
from . import user_all_reklama
from . import user_id_reklama