# Generated by Django 5.1.5 on 2025-01-17 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurslar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('nom_uz', models.CharField(max_length=255, null=True, verbose_name='Kurs nomi')),
                ('nom_ru', models.CharField(max_length=255, null=True, verbose_name='Kurs nomi')),
                ('tarif', models.TextField(verbose_name="Kursga ta'rif bering")),
                ('tarif_uz', models.TextField(null=True, verbose_name="Kursga ta'rif bering")),
                ('tarif_ru', models.TextField(null=True, verbose_name="Kursga ta'rif bering")),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='rasmlar/', verbose_name='Kurs rasmi')),
                ('matn', models.TextField(blank=True, null=True, verbose_name='Kurs uchun matn')),
                ('matn_uz', models.TextField(blank=True, null=True, verbose_name='Kurs uchun matn')),
                ('matn_ru', models.TextField(blank=True, null=True, verbose_name='Kurs uchun matn')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Malumotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admins', models.IntegerField()),
                ('last_message_sent_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Malumotlar',
                'verbose_name_plural': 'Malumotlar',
            },
        ),
        migrations.CreateModel(
            name='Obunachilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='Foydalanuvchi username')),
                ('full_name', models.CharField(max_length=150, null=True, verbose_name='Foydalanuvchining ismi')),
                ('phone_num', models.CharField(max_length=15, null=True, unique=True, verbose_name='Telefon raqami')),
                ('admin', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский')], default='uz', max_length=15, verbose_name='Til')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID ')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik vaqti')),
            ],
            options={
                'verbose_name': 'Obunachilar',
                'verbose_name_plural': 'Obunachilar',
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_subscribers', models.IntegerField(default=0, verbose_name='Barcha obunachilar')),
                ('for_last_month', models.IntegerField(default=0, verbose_name='Oxirgi oyda qushilganlar')),
                ('bot_users_within_24_hours', models.IntegerField(default=0, verbose_name='Botdan foydalanganlar (24 saot)')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
            },
        ),
        migrations.CreateModel(
            name='Xabar_yuborish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='Xabar turi')),
                ('content', models.TextField(blank=True, null=True, verbose_name="Matn, video yoki rasm uchun link jo'nating")),
                ('img', models.ImageField(blank=True, null=True, upload_to='images_uploaded')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('obunachilar', models.ManyToManyField(blank=True, to='informations.obunachilar')),
            ],
            options={
                'verbose_name': 'Xabar yuborish',
                'verbose_name_plural': 'Xabar yuborish',
            },
        ),
    ]
