# Generated by Django 5.1.5 on 2025-01-20 07:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='malumotlar',
            options={'verbose_name': 'Malumot', 'verbose_name_plural': 'Malumotlar'},
        ),
        migrations.AlterModelOptions(
            name='obunachilar',
            options={'verbose_name': 'Obunachi', 'verbose_name_plural': 'Obunachilar'},
        ),
        migrations.AlterModelOptions(
            name='statistika',
            options={'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistikalar'},
        ),
        migrations.RemoveField(
            model_name='kurslar',
            name='matn',
        ),
        migrations.RemoveField(
            model_name='kurslar',
            name='matn_ru',
        ),
        migrations.RemoveField(
            model_name='kurslar',
            name='matn_uz',
        ),
        migrations.AddField(
            model_name='malumotlar',
            name='obunachilar',
            field=models.ManyToManyField(related_name='Malumotlar', to='informations.obunachilar', verbose_name='Obunachilar'),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='tarif',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Kursga ta'rif bering"),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='tarif_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="Kursga ta'rif bering"),
        ),
        migrations.AlterField(
            model_name='kurslar',
            name='tarif_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name="Kursga ta'rif bering"),
        ),
        migrations.AlterField(
            model_name='malumotlar',
            name='admins',
            field=models.IntegerField(verbose_name='Adminlar'),
        ),
        migrations.AlterField(
            model_name='malumotlar',
            name='last_message_sent_date',
            field=models.DateTimeField(null=True, verbose_name='Oxirgi xabar yuborilgan'),
        ),
        migrations.AlterField(
            model_name='xabar_yuborish',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Xabar uchun matn jo'nating "),
        ),
    ]
