# Generated by Django 5.1.5 on 2025-01-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_alter_malumotlar_options_alter_obunachilar_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='malumotlar',
            name='obunachilar',
        ),
        migrations.AlterField(
            model_name='malumotlar',
            name='admins',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adminlar'),
        ),
    ]
