# Generated by Django 5.1.5 on 2025-01-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_remove_malumotlar_obunachilar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabar_yuborish',
            name='schedule_date',
            field=models.DateTimeField(blank=True, help_text="Agar vaqt ko'rsatilmasa, xabar darhol jo'natiladi.", null=True, verbose_name='Yuborish vaqti'),
        ),
    ]
