# Generated by Django 5.1.5 on 2025-01-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_xabar_yuborish_schedule_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='xabar_yuborish',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Yuborilganmi'),
        ),
    ]
