# Generated by Django 5.1.5 on 2025-01-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_xabar_yuborish_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xabar_yuborish',
            name='is_sent',
        ),
    ]
